/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.BufferedOutputStream;
import java.io.ObjectOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import metier.Reponse;

/**
 *
 * @author francois.monteil
 */
public class Client extends javax.swing.JFrame {

    private Socket client;
    private PrintWriter print;
    private Ecouteur ecouteur;
    private ObjectOutputStream streamOut = null;
    private Reponse reponse;
    
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        try {
            //On se connecte au serveur Kahoot
            this.connect();
            
            //On instancie la sortie
            streamOut = new ObjectOutputStream(new BufferedOutputStream(client.getOutputStream()));
            
            //On instancie un nouvel objet Ecouteur
            this.ecouteur = new Ecouteur(this.client, this.jTextArea_messages,
            this.jButton_rep1, this.jButton_rep2, this.jButton_rep3, this.jButton_rep4);
            this.ecouteur.start();
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Connect : essai de se connecter au serveur
     * @throws IOException 
     */
    private void connect() throws IOException
    {
        try{
        String local ="127.0.0.1";
        client = new Socket(local, 50000);
        }catch(IOException e)
        {
            System.out.println("Echec de la connexion au serveur");
            System.exit(1);
        }
        System.out.println("CLIENT - Connecté !");
        
        print = new PrintWriter(client.getOutputStream(), true);
    }
    
    /**
     * addTexte : Permet d'ajouter du texte dans la zone de dialogue
     * @param Qui
     * @param message 
     */
    public void addTexte(String Qui, String message)
    {
        this.jTextArea_messages.append(Qui+" : "+message+"\n");
    }    
    
    /**
     * dispose : redéfinition de la fonction dispose afin de se déconnecter du serveur
     */
    @Override
    public void dispose()
    {
        this.disconnect();    
        System.exit(0);
    }
    
    private void send(Reponse reponse)
    {
        try
        {
            streamOut.writeObject(reponse);
            streamOut.flush();
        }
        catch (IOException ex)
        {
            System.out.println("Erreur à l'envoi de la réponse - " +ex.getMessage());
        }
    }
    
    /**
     * disconnect : se déconnecte proprement du serveur
     */
    private void disconnect()
    {
        try {
            this.client.close();
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_messages = new javax.swing.JTextArea();
        jButton_rep4 = new javax.swing.JButton();
        jButton_rep1 = new javax.swing.JButton();
        jButton_rep3 = new javax.swing.JButton();
        jButton_rep2 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea_messages.setEditable(false);
        jTextArea_messages.setColumns(20);
        jTextArea_messages.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        jTextArea_messages.setRows(5);
        jTextArea_messages.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea_messages);

        jButton_rep4.setBackground(new java.awt.Color(0, 127, 1));
        jButton_rep4.setForeground(new java.awt.Color(255, 255, 255));
        jButton_rep4.setText("Reponse 4");

        jButton_rep1.setBackground(new java.awt.Color(240, 79, 59));
        jButton_rep1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_rep1.setText("Reponse 1");
        jButton_rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rep1ActionPerformed(evt);
            }
        });

        jButton_rep3.setBackground(new java.awt.Color(255, 149, 9));
        jButton_rep3.setForeground(new java.awt.Color(255, 255, 255));
        jButton_rep3.setText("Reponse 3");

        jButton_rep2.setBackground(new java.awt.Color(43, 56, 221));
        jButton_rep2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_rep2.setText("Reponse 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_rep1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_rep2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_rep4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton_rep2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_rep1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_rep4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rep1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_rep1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        new Client().setVisible(true);
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_rep1;
    private javax.swing.JButton jButton_rep2;
    private javax.swing.JButton jButton_rep3;
    private javax.swing.JButton jButton_rep4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_messages;
    // End of variables declaration//GEN-END:variables
}
