/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.BufferedOutputStream;
import java.io.ObjectOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import metier.Reponse;

/**
 *
 * @author francois.monteil
 */
public class Client extends javax.swing.JFrame {

    private Socket client;
    private PrintWriter print;
    private Ecouteur ecouteur;
    private ObjectOutputStream streamOut = null;
    private Reponse reponse;
    
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        try {
            //On se connecte au serveur Kahoot
            this.connect();
            
            //On instancie la sortie
            streamOut = new ObjectOutputStream(new BufferedOutputStream(client.getOutputStream()));
            
            //On instancie un nouvel objet Ecouteur
            this.ecouteur = new Ecouteur(this.client, this.jLabel_header,
            this.jButton_rep1, this.jButton_rep2, this.jButton_rep3, this.jButton_rep4);
            this.ecouteur.start();
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Connect : essai de se connecter au serveur
     * @throws IOException 
     */
    private void connect() throws IOException
    {
        try{
        String local ="127.0.0.1";
        client = new Socket(local, 50000);
        }catch(IOException e)
        {
            System.out.println("Echec de la connexion au serveur");
            System.exit(1);
        }
        System.out.println("CLIENT - Connecté !");
        
        print = new PrintWriter(client.getOutputStream(), true);
    }
        
    /**
     * dispose : redéfinition de la fonction dispose afin de se déconnecter du serveur
     */
    @Override
    public void dispose()
    {
        this.disconnect();    
        System.exit(0);
    }
    
    private void send(Object reponse)
    {
        try
        {
            streamOut.writeObject(reponse);
            streamOut.flush();
        }
        catch (IOException ex)
        {
            System.out.println("Erreur à l'envoi de la réponse - " +ex.getMessage());
        }
    }
    
    /**
     * disconnect : se déconnecte proprement du serveur
     */
    private void disconnect()
    {
        try {
            this.client.close();
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton_rep4 = new javax.swing.JButton();
        jButton_rep1 = new javax.swing.JButton();
        jButton_rep3 = new javax.swing.JButton();
        jButton_rep2 = new javax.swing.JButton();
        jLabel_header = new javax.swing.JLabel();
        jTextField_pseudo = new javax.swing.JTextField();
        jButton_pseudo = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton_rep4.setBackground(new java.awt.Color(0, 127, 1));
        jButton_rep4.setForeground(new java.awt.Color(255, 255, 255));
        jButton_rep4.setText("Reponse 4");
        jButton_rep4.setEnabled(false);
        jButton_rep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rep4ActionPerformed(evt);
            }
        });

        jButton_rep1.setBackground(new java.awt.Color(240, 79, 59));
        jButton_rep1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_rep1.setText("Reponse 1");
        jButton_rep1.setEnabled(false);
        jButton_rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rep1ActionPerformed(evt);
            }
        });

        jButton_rep3.setBackground(new java.awt.Color(255, 149, 9));
        jButton_rep3.setForeground(new java.awt.Color(255, 255, 255));
        jButton_rep3.setText("Reponse 3");
        jButton_rep3.setEnabled(false);
        jButton_rep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rep3ActionPerformed(evt);
            }
        });

        jButton_rep2.setBackground(new java.awt.Color(43, 56, 221));
        jButton_rep2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_rep2.setText("Reponse 2");
        jButton_rep2.setEnabled(false);
        jButton_rep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rep2ActionPerformed(evt);
            }
        });

        jLabel_header.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_header.setText("Kahoot");

        jTextField_pseudo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_pseudo.setText("Pseudo");

        jButton_pseudo.setText("Choisir");
        jButton_pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pseudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_header)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_rep4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_rep1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_rep2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_pseudo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel_header, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pseudo))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_rep1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_rep2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_rep3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_rep4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rep1ActionPerformed
        // TODO add your handling code here:
        send(ecouteur.getRep1());
    }//GEN-LAST:event_jButton_rep1ActionPerformed

    private void jButton_rep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rep2ActionPerformed
        // TODO add your handling code here:
        send(ecouteur.getRep2());
    }//GEN-LAST:event_jButton_rep2ActionPerformed

    private void jButton_rep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rep3ActionPerformed
        // TODO add your handling code here:
        send(ecouteur.getRep3());
    }//GEN-LAST:event_jButton_rep3ActionPerformed

    private void jButton_rep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rep4ActionPerformed
        // TODO add your handling code here:
        send(ecouteur.getRep4());
    }//GEN-LAST:event_jButton_rep4ActionPerformed

    private void jButton_pseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pseudoActionPerformed
        // TODO add your handling code here:
        send(this.jTextField_pseudo.getText());
        this.jTextField_pseudo.setEnabled(false);
        this.jButton_pseudo.setEnabled(false);
    }//GEN-LAST:event_jButton_pseudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        new Client().setVisible(true);
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_pseudo;
    private javax.swing.JButton jButton_rep1;
    private javax.swing.JButton jButton_rep2;
    private javax.swing.JButton jButton_rep3;
    private javax.swing.JButton jButton_rep4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel_header;
    private javax.swing.JTextField jTextField_pseudo;
    // End of variables declaration//GEN-END:variables
}
